FROM ghcr.io/muety/wakapi:latest

ENV WAKAPI_DB_TYPE="${WAKAPI_DB_TYPE:-sqlite3}"
ENV WAKAPI_DB_NAME="${WAKAPI_DB_NAME:-/data/wakapi/wakapi.db}"
ENV WAKAPI_DB_USER="${WAKAPI_DB_USER}"
ENV WAKAPI_DB_PASSWORD="${WAKAPI_DB_PASSWORD}"
ENV WAKAPI_DB_HOST="${WAKAPI_DB_HOST}"
ENV WAKAPI_DB_PORT="${WAKAPI_DB_PORT}"

ENV WAKAPI_PASSWORD_SALT="${WAKAPI_PASSWORD_SALT}"
ENV WAKAPI_LISTEN_IPV4="${WAKAPI_LISTEN_IPV4:-0.0.0.0}"
ENV WAKAPI_INSECURE_COOKIES="${WAKAPI_INSECURE_COOKIES:-false}"
ENV WAKAPI_ALLOW_SIGNUP="${WAKAPI_ALLOW_SIGNUP:-true}"

ENV ENVIRONMENT="${ENVIRONMENT:-prod}"

ENV PORT="${PORT:-3000}"
ENV WAKAPI_PORT="${PORT}"

USER root
